# Generated by Django 3.2.6 on 2021-08-21 16:06

from django.db import migrations, models
import operations.models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proganguser',
            name='profileImg',
            field=models.FileField(blank=True, null=True, upload_to=operations.models.get_profile_file),
        ),
    ]
