# Generated by Django 3.2.6 on 2021-08-24 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_proganguser_profileimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='proganguser',
            name='signupToken',
            field=models.TextField(blank=True, null=True),
        ),
    ]
